package com.nousguide.android.common.models

enum class Resource {
    RBTV_COVER_ART_PORTRAIT,
    RBTV_COVER_ART_LANDSCAPE,
    RBTV_COVER_ART_SQUARE,
    RBTV_COVER_ART_BANNER,
    RBTV_DISPLAY_ART_PORTRAIT,
    RBTV_DISPLAY_ART_LANDSCAPE,
    RBTV_DISPLAY_ART_SQUARE,
    RBTV_DISPLAY_ART_BANNER,
    RBTV_DISPLAY_ART_MONOCHROME,
    RBTV_BACKGROUND_PORTRAIT,
    RBTV_BACKGROUND_LANDSCAPE,
    RBTV_BACKGROUND_SQUARE,
    RBTV_BACKGROUND_BANNER,
    RBTV_TITLE_TREATMENT_SQUARE,
    RBTV_TITLE_TREATMENT_LANDSCAPE,
    RBTV_LOGO_SQUARE,
    RBTV_LOGO_LANDSCAPE,
    SHORT_PREVIEW_MP4_LOW,
    SHORT_PREVIEW_MP4_MEDIUM,
    SHORT_PREVIEW_MP4_HIGH,
    FULL_VIDEO,
    CLOSED_CAPTION_WEBVTT,
    CLOSED_CAPTION_TTML,
    UNKNOWN
}
